M48
; DRILL file {KiCad 7.0.2} date Mon May 15 10:15:10 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-05-15T10:15:10+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0827
%
G90
G05
T1
X6.798Y-2.2008
X6.8024Y-5.5016
X8.1457Y-5.5016
X8.1594Y-2.1969
T0
M30
