M48
; DRILL file {KiCad 7.0.5} date Wed May 31 19:25:18 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-05-31T19:25:18+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1378
%
G90
G05
T1
X0.7831Y-3.7083
X0.7835Y-0.8469
X2.0524Y-0.8457
X2.0551Y-3.7047
T0
M30
